name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    # services:
    # localstack:
    #   image: localstack/localstack:latest
    #   env:
    #     SERVICES: s3
    #     DEFAULT_REGION: eu-west-1
    #   ports:
    #     - 4566:4566
    #     - 4571:4571

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build
